### ISSUE TITLE
Changes to FunctionMath.Integrate

### ISSUE THREAD

**Issue by hayakawa16** [dcwuser/metanumerics#2]
My c# code has been using Meta.Numerics 1.3.0.0 and today I upgraded to 3.1.0.0.  Now some of my unit tests that call Integrate are failing.  I was able to change some values in my unit tests and now they pass.  However, I was interested in what changed with this code in between the two versions I list.

**Comment by dcwuser** [comment]
#hayakawa16: Looking back over the history of 3.0 to 3.1, I don't see any changes that _should_ have affected the behavior of FunctionMath.Integrate. Can you send me an example of code with changed output?

Thank you, by the way, for doing your own unit testing and reporting back results! And apologies for taking 3 days to get back to you; I am still getting used to the github notification model.

**Comment by hayakawa16** [comment]
Thanks for your response.  Actually I was at 1.3 not 3.0.  Any major changes from 1.3 to 3.1?

The previous code snippet using 1.3:
        public static double EvaluateDistributedExponentialLineSourceIntegral
            (Func<double, double> func, double muDecay)
        {
            Meta.Numerics.Function<double, double> integrand = zp =>
            {
                return func(zp) *
                    Math.Exp(-muDecay * zp);
            };
                FunctionMath.Integrate(
                    integrand,
                    Meta.Numerics.Interval.FromEndpoints(0.0, Double.PositiveInfinity));
        }

New code snippet using 3.1:
        public static double EvaluateDistributedExponentialLineSourceIntegral
            (Func<double, double> func, double muDecay)
        {
            Func<double, double> integrand = zp =>
            {
                return func(zp) *
                    Math.Exp(-muDecay * zp);
            };
                FunctionMath.Integrate(
                    integrand,
                    Meta.Numerics.Interval.FromEndpoints(0.0, Double.PositiveInfinity));
        }

We changed Meta.Numerics.Function to Func because Meta.Numerics.Function no longer exists.  

This method is part of a forward solver that is a standard diffusion approximation to the radiative transport equation for reflectance at r0 with a distributed line source.  The func being passed in is the difference between two Green's function solutions evaluated at distances that are a function of r0.  The unit test is an inverse solution test so it calls this method multiple times on the way to convergence.  I used to have r0 be [10,11,12,13,14,15] and it ran fine with version 1.3.  With 3.1 Integrate works for a while, then during the iterative process the Green's functions' parameters get updated and Integrate excepts with "Object reference not set to an instance of an object".  I updated my unit test to have r0 be [1,2,4,6,8,10] and 3.1 runs without error.  Since I have a work around it is not a problem, it was more a curiosity.
~

**Comment by dcwuser** [comment]
Thanks for the response. It's great to know Meta.Numerics is working on such an interesting problem! My own background is in physics, and I'm happy to say that I actually understand the general idea of your test problem.

There definitely have been some changes that affect integration since 1.3; it's not entirely trivial to track them all, since change history is usually tracked on the file level and the relevant code has changed files since then.

At first I had assumed that the change was simply a slightly different value being returned, or a different default accuracy level being targeted. But seeing a NullReferenceException raises my concern somewhat. That exception usually indicates a coding logic error and should basically never happen, so I'd really like to track it down.

If you are willing to help, there easiest next step would be to just copy the full stack trace from the exception. That will clarify if the problem is in the Integrate method itself, or in some other method in Meta.Numerics or in your code that it is calling in turn.

A next step, which would require more effort on your part, but enable me to move forward on my own, would be to zip up the test project and send it to me. I'm willing to send you a private email address so you don't have to post the code on github for all to see, and I'm willing to sign an NDA. If that's too much work or you simply aren't free to do so, I understand. Please do send the stack trace.

Thanks again.

**Comment by hayakawa16** [comment]
I'd be happy to help.  It is quite possible that something changed on our side that is causing the problem so this is helping me too.  In Visual Studio, I took a screen shot of the Exception Detail.  Then at the bottom there is an expansion of the Stack Trace and I copied that into a notepad file.  Let me know if I can provide any additional information.  Also, our code is hosted on GitHub (we just moved over from CodePlex too) so if it gets to that I can point you to the specifics.

<img width="948" alt="exceptionassitantdialog" src="https://cloud.githubusercontent.com/assets/26939347/26180504/b3e823c6-3b1e-11e7-9b69-e93db9c35700.PNG">
[ExceptionStackTrace.txt](https://github.com/dcwuser/metanumerics/files/1009347/ExceptionStackTrace.txt)

**Comment by dcwuser** [comment]
I was able to download VTS and repro the issue. It looks like my code is behaving badly, but it's triggered by your code behaving badly. :-) What's happening is that the function passed to Integrate is returning NaN for all inputs. Inside Meta.Numerics, that has the effect that the Integrate_Adaptive method estimates the error in every subrange as NaN, and since (NaN > anything) is false, it never finds the subrange with the maximum error, and maxNode is still null when its done checking all subranges.

I need to change my code to better defend against NaNs. But I suspect you will want to change your code to stop generating them. I haven't dug deep into where these NaNs are first appearing, but I do see that the DiffusionParameters argument passed into the StationaryFluence method has mueff = NaN, which is probably a clue. See the attached screenshot for context.

![debuggingvts](https://cloud.githubusercontent.com/assets/20149564/26186617/9f121fbe-3b47-11e7-951b-5818f292411f.png)

**Comment by hayakawa16** [comment]
Wow.  Thank you very much for your investigative work!  I will indeed look into why mueff is NaN. I was perplexed because although the test is an inverse solution which uses Levenberg-Marquardt and could have some randomness to the convergence, the final converged values always passed the test and have done so since 2010 when this unit test was first written.  mueff=sqrt[3*mua(mua+mus')] and mua and mus' are parameters being sought in the inverse solution and are physically positive values.  The L-M algorithm convergence path must have changed slightly such that one of these values is going negative. I've seen this happen with other forward solvers and still converge appropriately, however, in this SDA solution it creates a problem due to the sqrt.  I'll have to think upon this more to determine the best fix in our code, but I wanted to get back to you quickly and let you know how much I appreciate your help.

**Comment by hayakawa16** [comment]
I just wanted to follow up.  I added a constrained Levenberg-Marquardt method to our software and now call that in our unit tests constraining the parameters lower bound to be zero.  Now the original unit tests pass fine and MetaNumerics is happier too.  Thanks again for your help with this.

**Comment by dcwuser** [comment]
For integration, map NaN to zero. Added test case.
