### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by lklauder** [dcwuser/metanumerics#40]
When I try with VS 2017 to load the solution  file of metanumerics-4.0.7 I get the error:

E:\dev\code_library\numerical\meeta.numerics\metanumerics-4.0.7\Numerics\Numerics.csproj : error  : The expression "[System.IO.Path]::Combine(C:\Users\lou\AppData\Local\Temp\, .NETPortable,Version=v5.0,Profile=
    .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

**Comment by dcwuser** [comment]
It was developed in VS 2015. After the 4.0.7 release, I moved to VS 2017. I did encounter some issues during that transition, but not an illegal path issue. I will attempt to repro. Is it critical that you be able to work on the 4.0.7 branch in VS 2017, or is it fine as long as the development branch works in VS 2017?

**Comment by lklauder** [comment]
Hi Dave;

Thanks for responding.

My motive is that I am struggling with an issue in a regression test program that uses parallel.foreach in order to get better speed as the application being tested processes multiple input files. It worked back in 2012, but something I added in the meantime has caused it to fail. A lot of people have had similar problems, but I have not found my answer yet. One suggestion was to get everything targeting x64, and I wanted to compile an instance of  Meta.Numerics with that target.

Relative to the output complaint that I posted: the error msg referenced a file in   …\Microsoft Visual Studio\Preview\Community even though I had tried to open it in the released version of VS 2017. In case there was an anomaly in one of the VS installations, I deinstalled the Preview and tried again. The problem persists with the message now reading:

E:\dev\code_library\numerical\meeta.numerics\metanumerics-4.0.7\Numerics\Numerics.csproj : error  : The expression "[System.IO.Path]::Combine(C:\Users\lou\AppData\Local\Temp\, .NETPortable,Version=v5.0,Profile=
    .AssemblyAttributes.cs)" cannot be evaluated. Illegal characters in path.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

I glanced at the   Numerics.csproj  and Microsoft.Common.CurrentVersion.targets files, and the problem seems to be in the statement:
Condition="'$(TargetFrameworkMonikerAssemblyAttributesPath)' == ''">$([System.IO.Path]::Combine('$([System.IO.Path]::GetTempPath())','$(TargetFrameworkMoniker).AssemblyAttributes$(DefaultLanguageSourceExtension)'))
And in particular in the value of::
$(TargetFrameworkMoniker).AssemblyAttributes$(DefaultLanguageSourceExtension)
Trying to figure that out would take me a bit farther into the weeds than I am comfortable going. Hopefully you are more familiar with such stuff than I am.


I also tried my luck with  version 3.1.0.  I could compile the library ok, but when I tried to load the .sln file in the top folder I got the complaints:

E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Core\Core.csproj : error  : The project file could not be loaded. Could not find a part of the path 'E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Core\Core.csproj'.  E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Core\Core.csproj

E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Web\Web.csproj : error  : The project file could not be loaded. Could not find a part of the path 'E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Web\Web.csproj'.  E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Web\Web.csproj

E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Extensions\Extensions.csproj : error  : The project file could not be loaded. Could not find a part of the path 'E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Extensions\Extensions.csproj'.  E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Extensions\Extensions.csproj

E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Graphics\Graphics.csproj : error  : The project file could not be loaded. Could not find a part of the path 'E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Graphics\Graphics.csproj'.  E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Graphics\Graphics.csproj

E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Plotting\Plotting.csproj : error  : The project file could not be loaded. Could not find a part of the path 'E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Plotting\Plotting.csproj'.  E:\dev\code_library\numerical\meeta.numerics\metanumerics-3.1.0\Plotting\Plotting.csproj

The Numerics folder contained a core folder but the latter did not contain a .csproj file. Superficially, the above look to me like configuration inconsistencies in the source distribution of that version.

Hope the above is helpful.

Lou Klauder

**Comment by dcwuser** [comment]
Okay, I am able to repro. The problem is that the Numerics project uses the .NET Portable project framework, which doesn't exist for VS2017 -- it's been replaced by .NET Standard. To work with the project in VS2017, you have to convert the project to .NET Portable. Fortunately, that's not too hard. (Also, I did it anyway for the next version, so you are not diverging from the development path by doing so.) I'll send instructions as soon as I figure out the best way to transmit the file to you.

**Comment by dcwuser** [comment]
I have created a new branch, Numerics-v4, which is the released 4.0.7 code with just the project changes required to get it to load and build in VS2017. If you are familiar with git, you can clone that branch (not master) to your machine and you should be able to simply open and build in VS2017.

Alternatively, you can modify your existing snapshot of the 4.0.7 code as follows: replace the Numerics.csproj file with https://github.com/dcwuser/metanumerics/blob/Numerics-v4/Numerics/Numerics.csproj (yes, the content is much simpler). Then either delete the AssemblyInfo.cs file entirely, or replace it with https://github.com/dcwuser/metanumerics/blob/Numerics-v4/Numerics/Properties/AssemblyInfo.cs (again, the new content is much simpler). You should then be able to re-load and build.

By the way, please feel free to ask for my help in tracking down your regression issue. I want to make sure it's not due to any change I have made in the library.
