### ISSUE TITLE
Version 4.0.7 does not support .NET Framework 4.0 even though it is listed in release

### ISSUE THREAD

**Issue by PawelTroka** [dcwuser/metanumerics#43]
In release 4.0.7 (https://github.com/dcwuser/metanumerics/releases/tag/v4.0.7) we can see that .NET Framework 4.0 is listed:
```
Targets .NET Standard 1.1 (.NET Framework 4.0 or higher or .NET Core)
```
but actually according to Microsoft .NET Standard 1.1 is only supported by .NET Framework 4.5+ (https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.1.md)

**Comment by dcwuser** [comment]
You are correct. I have corrected the release description to say .NET Framework 4.5. Thanks for the bug report.

**Comment by PawelTroka** [comment]
Actually I hoped you may consider supporting .NET Framework 4.0 :)

**Comment by dcwuser** [comment]
I will try to compile the code under Framework 4.0 and make it available as a private branch release. But it would be difficult to do a public, long-term supported Framework 4.0 release.

1. It would mean giving up on .NET Standard. There is simply no .NET Standard version that supports Framework 4.0.

2. The project file format for .NET Standard is different than for .NET Framework. That means even if the code is compatible, I would need to maintain a separate project file.

3. I actually want to move forward to .NET Standard 2.0 soon, because I want to add APIs that do file and web I/O (e.g. load CSV from file path), and those are not supported in .NET Standard 1.1.

I will let you know how the attempt to compile under Framework 4.0 goes.
