### ISSUE TITLE
MPFit.Solve Exception

### ISSUE THREAD

**Issue by hayakawa16** [dcwuser/metanumerics#47]
Hi,
I'm using MPFit.Solve to solve inverse problems.  My code references Meta.Numerics version 4.0.7.0.  I have a set of input parameters which are throwing a NonconvergenceException, i.e. the algorithm did not converge within the allowed number of iterations. I have attached a screen shot of the exception.
<img width="960" alt="mpfitexception" src="https://user-images.githubusercontent.com/26939347/42475526-c1877874-837f-11e8-993c-98131faca6a1.PNG">
I wondered if this exception could be handled and passed back to the user via the return status.
Please let me know if I can provide any additional data that would help debug this issue.
Thanks for your help!
Best regards,
Carole

**Comment by dcwuser** [comment]
Thanks for reporting this.

There are few different places where Meta.Numerics uses NonconvergenceException. Some of them (e.g. inside our own special function evaluations) would indicate a bug in Meta.Numerics. Others (e.g. when numerically integrating a user-supplied function with a too-small budget) would indicate a user error. To know what's going on here, it would be helpful to see the full stack trace, including the inner exception stack trace.

TargetInvocationException usually indicates that you are invoking a method dynamically via reflection. That shouldn't itself be a problem, but in this case it is causing the NonconvergenceException that the Meta.Numerics code throws to be wrapped up inside the TargetInvocationException that the BCL reflection code throws.

If I understand your suggestion correctly, you are asking that, at least in the cases where we are operating on some user-supplied function, instead of throwing NonconvergenceException, we add a property to the returned EvaluationResult that indicates that the requested precision was not achieved. Is that right? I worry a bit that it becomes too easy for people to write code that ignores the failure, but I do see the value of such an option in the right hands. Probably I would do it by adding it as a default-false option that could be set on the optional EvaluationSettings that the user can pass in. Would that address your requirements or am I misunderstanding your ask?

Thanks again. I look forward to your feedback.

**Comment by hayakawa16** [comment]
I am embarrassed....the error that I am getting is not coming from your software, it is coming from another dll.  I'm sorry to bother and trouble you.
Best,
Carole

**Comment by dcwuser** [comment]
Hi Carole,

Please don't be embarrassed. Looking at your screen-shot, I suspect that the original exception is indeed coming from Meta.Numerics, because we define the type NonconvergenceException and are probably the code that throws it. It is being filtered through one or more software layers which depend on Meta.Numerics. It won't hurt to pull them to this discussion, and ultimately the right solution might be for them to invoke Meta.Numerics differently. But the right solution might also be for Meta.Numerics to behave differently, and your suggestion for how it should is a valuable one.

Please keep me in the loop as you deal with this issue.

**Comment by hayakawa16** [comment]
Dear David,
Thank you very much for your email.  I plan to pull in the code that calls Meta.Numerics and Meta.Numerics code into our solution today and see if I can step through the problem.  I appreciate your quick responses and support!
Carole

**Comment by hayakawa16** [comment]
Hi David,

I stepped through the code and was able to determine a solution that makes sense for us and requires no code change to other software.  The problem is related to the problem I posted to your site last year and has to do with having optical properties that go negative during optimization iterations and this causes the Meta Numerics Integrate to have an exception.  The previous fix was to call a constrained optimization method rather than an unconstrained method and I did not hesitate to make the fix because the problem was occurring our unit tests and did not affect anyone else.  This time the change to constrained optimization is within our public GUI so requires a little more care.  In any event, just wanted to let you know that all is good now. 

Thanks again for your continued help.
Best, Carole
