### ISSUE TITLE
Is it possible to use the library with streaming data?

### ISSUE THREAD

**Issue by astef** [dcwuser/metanumerics#55]
I need to count mean and variance without keeping all the samples in the memory. They will be arriving in a large amount from a remote source and there's no practical reason to keep the data in memory.

Is it possible with the library?

**Comment by dcwuser** [comment]
Yes. The SummaryStatistics class in the Meta.Numerics.Statistics namespace does exactly this. Create a new instance and call Add with your data. It does not remember your data, but updates fixed-size internal registers so that you can get Mean, Variance, Skewness, Minimum, Maximum, and corresponding population moment estimates for all data added so far.
