### ISSUE TITLE
StandardDeviation VS PopulationStandardDeviation.Value

### ISSUE THREAD

**Issue by TruePluto** [dcwuser/metanumerics#9]
I use Meta.Numeric to process my data automatically. But the result confused me. I  analysed a list of data( double)  via sample to get Min Max Mean and StandardDeviation. everything is ok except StandardDeviation. it is diffirent with the result come from SPSS. 
so I check my code and output more data result. such as PopulationStandardDeviation. 
the PopulationStandardDeviation.value matched the SPSS' StandardDeviation. So I confused.
I'm not good at statiscs. I am not sure that  PopulationStandardDeviation.value is  StandardDeviation.

Does anybody tell me what mistake i made?
Thank you.

**Comment by TruePluto** [comment]
Tody Isee the source code of 

```
 public double Variance {
            get {
                // Note this is the sample variance, not the population variance
                return (M2 / N);
            }
        }

```
actually this is population variance and the variance is return (M2/(N-1));

**Comment by dcwuser** [comment]
The variance (and corresponding standard deviation) computed by dividing the sum of squared deviations by (N-1) is an unbiased estimate of the variance of the population that underlies the sample. The variance computed by dividing by N is the variance of the sample data. To make it easier to distinguish these concepts, Meta.Numerics names any method that computes moment X of the sample "X" and any method that computes an estimate of the corresponding moment of the underlying population as "PopulationX". Note that the former is an exact number (and thus a double) and the latter has an uncertainty (and thus an UncertainValue).

Since most users are likely to want the unbiased estimate of population property, SPSS has chosen to give the simple name "StandardDeviation" to it. I, on the other hand, have given higher priority to drawing a clear distinction between sample quantities and population estimates. As long as you know what you are looking for, you can get either quantity out of either framework.

**Comment by TruePluto** [comment]
@dcwuser I think that We have learnt different statistics courses. I'm still confused, But thank you. except this, Meta.Numerics is a brilliant package. 

>

**Comment by TruePluto** [comment]
@dcwuser I think that We have learnt different statistics courses. I'm still confused, But thank you. except this, Meta.Numerics is a brilliant package.

**Comment by dcwuser** [comment]
Thanks for writing back. It's true that Wikipedia uses "sample standard deviation" and "population standard deviation" opposite to my convention. But the convention is nowhere near universal. Mathworld, for example, uses my definitions: http://mathworld.wolfram.com/StandardDeviation.html and http://mathworld.wolfram.com/SampleVariance.html. About this confusing situation, I would note:

1. Mathworld is also upfront about the fact that there are conflicting conventions: "The distinction ... is a common source of confusion, and extreme care should be exercised when consulting the literature to determine which convention is in use" and "However, consistent with widespread inconsistent and ambiguous terminology, the square root of the bias-corrected variance is sometimes also known as the standard deviation".

2. Wikipedia itself isn't actually so clear-cut. It does define "sample standard deviation" as the (n-1)-thing. But it also defines "standard deviation of the sample" as the n-thing. It's not actually clear which of those two things a property named "StandardDeviation" or a class named "Sample" should return.

3. While the (n-1) thing is an unbiased variance estimator, it's square root is not actually an unbiased standard deviation estimator (because \sqrt\{E(x)\} \ne E(\sqrt\{x\})). So this very popular very popular (n-1)-thing is neither the standard deviation of the sample values nor the best estimator of the standard deviation of the underlying distribution.

Still, I admit that most software packages (including Mathematica) bow to its popularity and return the (n-1) thing from their "StandardDeviation" function. I am updating the documentation to be clearer, and will try to find names that are clearer for the next release. Please don't hesitate to continue to provide feedback as bugs or feature requests.
